name: tests

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run prepack
      - run: npm run test
      - run: |
          cd example/react-native/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew assembleRelease
          test app/build/outputs/apk/debug/app-debug.apk