name: tests

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run prepack
      - run: npm run test
